name: todo_app
description: A simple Flutter To-Do app.

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  flutter_slidable: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
environment:
  sdk: '^3.5.0'